AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

MultilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/ParameterLists:
  Max: 10

Metrics/BlockLength:
  Max: 30

Style/SpecialGlobalVars:
  Enabled: false
